### ISSUE TITLE
Closed li tag visible on UI

### ISSUE THREAD

**Issue by ggarciasoft** [cryptowarz/website-bugs#24]
A _closed li tag_ is visible on the UI under _Tasks -> 1.04 Withdraw Stake_ section.
![image](https://user-images.githubusercontent.com/7860320/119200520-13afa300-ba5b-11eb-9ad6-0da90f343046.png)

**Comment by cryptowarz** [comment]
Solid find - 👍  Fixed.  
It was database driven - so just had to update DB to close the LI. 
Thanks for pointing this out.

**Comment by cryptowarz** [comment]
Submit a bug task and reference this ticket - I'll give you some extra tokens.

**Comment by ggarciasoft** [comment]
Where can I submit the task?

**Comment by cryptowarz** [comment]
Number 1.11 at the following link: 
https://cryptowarz.net/app/tasks   
Thank you !!
